half project
pavelbutko1998/lampShop pull request #1
Opened 2021-01-13 13:17 UTC by pavelbutko1998

2021-01-13 17:47 UTC, justiceteam-it requested changes

2021-01-13 17:47 UTC, justiceteam-it commented on package.json
> +    "jquery": "^1.12.4",
what is it?

2021-01-13 17:47 UTC, justiceteam-it commented on src/component/Card/Card.js
> +import './Card.scss';
ask Viktor about place dependencies

2021-01-13 17:47 UTC, justiceteam-it commented on src/component/Nav/Nav.js
> +export default function Nav(){
use arrow func

2021-01-13 17:47 UTC, justiceteam-it commented on src/component/Sign/Buttonform.js
> +export default function Btnform (props) {
same to

2021-01-13 17:47 UTC, justiceteam-it commented on src/component/Sign/Buttonform.js
> +import React, {Component, createElement} from 'react';
tell me where to place these dependencies? {Component, createElement}

2021-01-13 17:47 UTC, justiceteam-it commented on src/component/Sign/Emailform.js
> +export default function Emailform () {
same

2021-01-13 17:47 UTC, justiceteam-it commented on src/component/Sign/Nameform.js
> +export default function Nameform () {
same

2021-01-13 17:47 UTC, justiceteam-it commented on src/component/Sign/Signin.js
> +
empty place

2021-01-13 17:47 UTC, justiceteam-it commented on src/component/Sign/Signin.js
> +import Btnform from "./Buttonform";
same to

2021-01-13 18:12 UTC, Viktor-Web-Dev commented on src/App.js
> +export default function App() {
const App = () => (
<div> ...
);
export default App;

2021-01-13 18:13 UTC, Viktor-Web-Dev commented on src/component/Card/Card.scss
> +
Удали пробел

2021-01-13 18:38 UTC, Viktor-Web-Dev requested changes

2021-01-13 18:38 UTC, Viktor-Web-Dev commented on src/component/Heart/Heart.js
> +export default function Heart() {
...

2021-01-13 18:38 UTC, Viktor-Web-Dev commented on src/component/Nav/Nav.js
> +import Signup from "../Sign/Signup";
Используй одинарные кавычки при импорте

2021-01-13 18:38 UTC, Viktor-Web-Dev commented on src/component/Nav/Nav.js
> +                            <NavLink to="/starter" className="nav_link" exact activeClassName="active" >Starter Store</NavLink>
лишний пробел
и если у тебя идет больше трех перечислений выноси все на отдельные строчки, так код становится более читаемый

2021-01-13 18:38 UTC, Viktor-Web-Dev commented on src/component/Nav/Nav.js
> +                            <div className="wrapper_main">
добавь key

2021-01-13 18:38 UTC, Viktor-Web-Dev commented on src/component/Nav/Nav.scss
> +.nav_wrapper{
пробел

2021-01-13 18:38 UTC, Viktor-Web-Dev commented on src/component/Nav/Nav.js
> +    document.querySelector('.bottom_col').classList.toggle('menu_active');
использовать querySelector не бест практис, нужно переделать

2021-01-14 10:45 UTC, justiceteam-it requested changes

2021-01-14 10:45 UTC, justiceteam-it commented on src/App.js
check it

2021-01-14 10:45 UTC, justiceteam-it commented on src/component/Card/Card.js
> +            <img src={props.img} alt="lapm1"/>
make 'alt' dynamic

2021-01-14 10:45 UTC, justiceteam-it commented on src/component/Heart/Heart.js
> +        <img className="i_lamp_img" src={HeartImg} alt="lamp"/>
in column

2021-01-14 10:45 UTC, justiceteam-it commented on src/component/Nav/Nav.js
> +        document.querySelector('.bottom_col').classList.toggle('menu_active');
maybe, we can use ref or flags. In react use 'document' - bad solution

2021-01-14 10:45 UTC, justiceteam-it commented on src/component/Sign/Passform.js
> +        <label htmlFor="">
htmlFor - 
why is it?

2021-01-14 12:04 UTC, merged